### PR TITLE
Fix for semantic  check complaining when resetting numeric field to empty string

### LINKED ISSUE #3525: Once a milestone range is set, it cannot be cleared
**Describe the bug**
I tried to remove the OT milestones for a feature entry and found that it complained that the end needed to be after the start.

**To Reproduce**
1. Go to a feature entry that has start and end OT milestones set
2. Clear out both fields
3. Submit
4. See field error on both fields, preventing submission.

**Expected behavior**
It should be allowed to have one of both fields empty, even if they were previously set.

### PR DESCRIPTION
**Pull request by dlaliberte**
This PR fixes #3525 by checking for empty string explicitly to return an undefined value rather than converting it to 0.

### CODE REVIEW

File: client-src/elements/utils.js [hunk 1]
```diff
@@ -387,12 +387,14 @@ export function checkMilestoneStartEnd(startEndPair, getFieldValue) {
...
     const value = getFieldValue(name);
     if (typeof value === 'string') {
+      if (value === '') return undefined;
       return Number(value);
     }
   };
   const {start, end} = startEndPair;
   const startMilestone = getValue(start);
   const endMilestone = getValue(end);
+  console.info(`after getValue: start: ${startMilestone} end: ${endMilestone}`);
```
Comment (jrobbins) [inline client-src/elements/utils.js:397]: Is this console output still needed?

**Review by jrobbins — APPROVED** [review]
LGTM after addressing one comment.
