### PR TITLE
Fix Gantt chart to use new milestone fields

### LINKED ISSUE #2901: Origin Trial milestones are entered but "No milestones specified" is displayed
**Describe the bug**
I've selected Origin Trial milestones for my feature (WasmGC) but the message "No milestones specified" is displayed on the main info page.

**To Reproduce**
1. Go to https://chromestatus.com/feature/6062715726462976
2. Open "Origin Trial" dropdown
3. See that "OT Desktop/Android" start and end milestones are selected (112 and 117)
4. Scroll back up to top
5. Under "Implementation status: Origin Trial", see "No milestones specified" 

**Expected behavior**
The milestones would be listed in the main info box.

### PR DESCRIPTION
**Pull request by DanielRyanSmith**
Fixes #2901 

The functionality for the feature milestones Gantt chart was broken due to the removal of the old milestone fields on the Feature JSON representation. This PR updates the old references to use the stage milestone fields to populate the Gantt chart instead.

Note that this fixes the initial issue that broke the Gantt chart, but additional work is still required to accommodate multiple stages in the new schema.

### CODE REVIEW

File: client-src/elements/chromedash-gantt.js [hunk 1]
```diff
@@ -128,6 +133,26 @@ class ChromedashGantt extends LitElement {
...
+        dtStages.push(stage);
+      } else if (STAGE_TYPES_ORIGIN_TRIAL.has(stage.stage_type)) {
+        otStages.push(stage);
+      } else if (STAGE_TYPES_SHIPPING.has(stage.stage_type)) {
+        shipStages.push(stage);
+      }
+    }
+
+    // TODO(DanielRyanSmith): Fix this to support multiple stages.
+    return [dtStages[0], otStages[0], shipStages[0]];
```
Comment (jrobbins) [inline client-src/elements/chromedash-gantt.js:154]: Could one of these lists be empty?  I suppose that returning `undefined` is OK.

**Review by jrobbins — APPROVED** [review]

File: client-src/elements/chromedash-gantt.js (hunk 1 above)
Comment (DanielRyanSmith) [reply client-src/elements/chromedash-gantt.js:154]: Yes, my first thought process was to check if any list was empty, but JS will just return undefined for out of bounds accesses. If this code was supposed to be permanent, I'd make this more explicit, but ideally we update this to handle the new schema accurately anyway.
